default-job: Unemployed
jobs:
    - Unemployed
    - Lumberjack
    - Miner
    - Farmer
    - Hunter
forbbiden-prefixes:
	- IRC
party:
    allowed: true
    default-slots: 5
    share-self: 70
    share-others: 30
    radius: 25
job:
    default-job: Unemployed
    default-exp-formula: "150*(1.34^l)"
    default-reward-formula: "9.8*(1.2^l)"
    default-exp-modifier: 1.0
    default-reward-modifier: 1.0
    default-job-status: true